# Generated by Django 3.2.1 on 2021-05-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_flag', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('availabilityFlag', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_field', models.FileField(upload_to='user1')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('availabilityFlag', models.BooleanField(default=True)),
                ('result_text', models.TextField(blank=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30)),
                ('timestamp', models.DateField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_flag', models.BooleanField(default=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('prover_name', models.CharField(blank=True, max_length=30)),
                ('status_data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('timestamp', models.DateField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.sectioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('validity_flag', models.BooleanField(default=True)),
                ('line_nr', models.IntegerField(default=0)),
                ('ref_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.sectioncategory')),
                ('ref_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.file')),
                ('ref_status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.sectionstatus')),
                ('ref_status_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.statusdata')),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.directory'),
        ),
    ]
